version: '3.9'

services:
  db:
    image: postgres:16-alpine
    container_name: dcm_proj_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-dcm_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-dcm_pass}
      POSTGRES_DB: ${DB_NAME:-dcm_db}
    ports:
      - '${DB_PORT:-5432}:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
